FROM golang:1.12

ENV GO111MODULE=on

WORKDIR /app

# cache go modules
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

EXPOSE 9000

RUN make build

# TODO pass environment variables
ENTRYPOINT ["./dist/pushaas"]